global:
  scrape_interval: 15s

scrape_configs:
  # 앱 EC2(MarketON) Spring Boot actuator
  - job_name: 'dongnemarket-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['10.0.2.155:8080']   # 앱 EC2 프라이빗 IP
        labels:
          application: 'dongnemarket'
